import { writeFileSync } from 'fs';

const lines = [
  "/**",
  " * @license",
  " * SPDX-License-Identifier: Apache-2.0",
  " */",
  "",
  'import { useState, useEffect, useMemo } from "react";',
  'import Header from "./components/Header";',
  'import Footer from "./components/Footer";',
  'import Sidebar from "./components/Sidebar";',
  'import HomePage from "./components/HomePage";',
  'import CategoryPage from "./components/CategoryPage";',
  'import PostDetailPage from "./components/PostDetailPage";',
  'import LoginPage from "./components/LoginPage";',
  'import EditorPage from "./components/EditorPage";',
  'import AdminPage from "./components/AdminPage";',
  'import { Category, MOCK_POSTS, slugToCategory, categoryToSlug } from "./types";',
  "",
  "interface NavState {",
  '  page: "home" | "category" | "post" | "login" | "editor" | "admin";',
  "  category: Category | null;",
  "  postId: string | null;",
  "}",
  "",
  "export default function App() {",
  "  const [navState, setNavState] = useState<NavState>({",
  '    page: "home",',
  "    category: null,",
  "    postId: null,",
  "  });",
  "",
  '  const [searchQuery, setSearchQuery] = useState("");',
  "",
  "  useEffect(() => {",
  "    const parseHash = () => {",
  '      const hash = window.location.hash || "#/";',
  '      if (hash === "#/" || hash === "") { setNavState({ page: "home", category: null, postId: null }); return; }',
  '      if (hash === "#/login") { setNavState({ page: "login", category: null, postId: null }); return; }',
  '      if (hash === "#/editor") { setNavState({ page: "editor", category: null, postId: null }); return; }',
  '      if (hash === "#/admin") { setNavState({ page: "admin", category: null, postId: null }); return; }',
  "      const categoryMatch = hash.match(/^#\\/categoria\\/([^/]+)$/);",
  '      if (categoryMatch) { const m = slugToCategory(categoryMatch[1]); if (m) { setNavState({ page: "category", category: m, postId: null }); return; } }',
  "      const postMatch = hash.match(/^#\\/post\\/([^/]+)$/);",
  '      if (postMatch) { setNavState({ page: "post", category: null, postId: postMatch[1] }); return; }',
  '      setNavState({ page: "home", category: null, postId: null });',
  "    };",
  "    parseHash();",
  '    window.addEventListener("hashchange", parseHash);',
  '    return () => { window.removeEventListener("hashchange", parseHash); };',
  "  }, []);",
  "",
  '  const handleNavigateHome = () => { setSearchQuery(""); window.location.hash = "#/"; };',
  "  const handleNavigateCategory = (cat: Category) => { setSearchQuery(\"\"); window.location.hash = `#/categoria/${categoryToSlug(cat)}`; };",
  "  const handleNavigatePost = (postId: string) => { window.location.hash = `#/post/${postId}`; };",
  '  const handleSearchChange = (query: string) => { setSearchQuery(query); if (navState.page !== "home" && query.trim().length > 0) { window.location.hash = "#/"; } };',
  "",
  "  const activeCategoryForHeader = useMemo(() => {",
  '    if (navState.page === "category") return navState.category;',
  '    if (navState.page === "post" && navState.postId) { const p = MOCK_POSTS.find((p) => p.id === navState.postId); return p ? p.category : null; }',
  "    return null;",
  "  }, [navState]);",
  "",
  '  const isFullPage = navState.page === "login" || navState.page === "editor" || navState.page === "admin";',
  "",
  "  return (",
  '    <div className="bg-[#F9FAFB] text-[#0e1c2e] min-h-screen flex flex-col antialiased">',
  "      <Header currentCategory={activeCategoryForHeader} currentPage={navState.page} onNavigateHome={handleNavigateHome} onNavigateCategory={handleNavigateCategory} />",
  '      <main className={`flex-grow w-full ${isFullPage ? "" : "max-w-[1280px] mx-auto px-4 md:px-8 py-8 flex flex-col lg:flex-row gap-8"}`}>',
  '        <div className={